# -*- coding: utf-8 -*-

__title__ = 'Acquire Coordinates'
__doc__ = """
This script will specifically use
to acquire the coordinates of the
first link model.
================================
HOW TO:
1. On the Active View, make sure the
only link visible is the link you
would want to acquire the coordinates.
2. Click the button.
3. Profit.
__________________________________
v1: 10 Oct 2023
Author: Joven Mark Gumana
"""


# ╦╔╦╗╔═╗╔═╗╦═╗╔╦╗
# ║║║║╠═╝║ ║╠╦╝ ║
# ╩╩ ╩╩  ╚═╝╩╚═ ╩ # imports
# ===================================================================================================
from Autodesk.Revit.DB import *
from pyrevit import forms

import clr
clr.AddReference("System")
from System.Collections.Generic import List



# ╦  ╦╔═╗╦═╗╦╔═╗╔╗ ╦  ╔═╗╔═╗
# ╚╗╔╝╠═╣╠╦╝║╠═╣╠╩╗║  ║╣ ╚═╗
#  ╚╝ ╩ ╩╩╚═╩╩ ╩╚═╝╩═╝╚═╝╚═╝# variables
# ======================================================================================================
doc      = __revit__.ActiveUIDocument.Document
uidoc    = __revit__.ActiveUIDocument
app      = __revit__.Application

active_view     = doc.ActiveView
active_level    = doc.ActiveView.GenLevel

link_collect = FilteredElementCollector(doc, active_view.Id).OfClass(RevitLinkInstance)

lk = link_collect.FirstElement()

link_id = lk.Id

# ╔╦╗╔═╗╦╔╗╔
# ║║║╠═╣║║║║
# ╩ ╩╩ ╩╩╝╚╝#main
# =========================================================================================================
with Transaction(doc, __title__) as t:
    t.Start()

    doc.PublishCoordinates(link_id)

    t.Commit()